const github = {
    login: 'ECIZEP',
    id: 11472792,
    node_id: 'MDQ6VXNlcjExNDcyNzky',
    avatar_url: 'https://avatars3.githubusercontent.com/u/11472792?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ECIZEP',
    html_url: 'https://github.com/ECIZEP',
    followers_url: 'https://api.github.com/users/ECIZEP/followers',
    following_url: 'https://api.github.com/users/ECIZEP/following{/other_user}',
    gists_url: 'https://api.github.com/users/ECIZEP/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ECIZEP/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ECIZEP/subscriptions',
    organizations_url: 'https://api.github.com/users/ECIZEP/orgs',
    repos_url: 'https://api.github.com/users/ECIZEP/repos',
    events_url: 'https://api.github.com/users/ECIZEP/events{/privacy}',
    received_events_url: 'https://api.github.com/users/ECIZEP/received_events',
    type: 'User',
    site_admin: false,
    name: 'ECIZEP',
    company: null,
    blog: '',
    location: null,
    email: null,
    hireable: null,
    bio: '路漫漫其修远兮',
    public_repos: 18,
    public_gists: 1,
    followers: 6,
    following: 4,
    created_at: '2015-03-14T10:08:20Z',
    updated_at: '2018-08-26T15:56:15Z',
    private_gists: 0,
    total_private_repos: 0,
    owned_private_repos: 0,
    disk_usage: 33544,
    collaborators: 0,
    two_factor_authentication: false,
    plan: {
        name: 'free',
        space: 976562499,
        collaborators: 0,
        private_repos: 0
    }
}

const google = {
    id: '111797615711812551289',
    email: 'ecizep@gmail.com',
    verified_email: true,
    name: 'Orange Chan',
    given_name: 'Orange',
    family_name: 'Chan',
    link: 'https://plus.google.com/111797615711812551289',
    picture: 'https://lh4.googleusercontent.com/-WdWX083qG70/AAAAAAAAAAI/AAAAAAAAAAA/ABtNlbAfWNsKU89QNhpjBFOuJ8Y1GbUrnw/mo/photo.jpg',
    locale: 'zh-CN'
}